spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    data:
        web:
            pageable:
                one-indexed-parameters: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
                show_sql: true
properties:
    external:
        auth0:
            audience: ${AUTH0_AUDIENCE}
            issuer: https://${AUTH0_DOMAIN}/
